/* Storm in a Teacup: the idiom library. Every meaning and origin note is written for this site; origins are labelled by how solid the evidence is. */
window.IDIOMS = [
  { id:"horse", pre:"You can't flog a dead", word:"horse", emo:"🐴", post:"", decoys:[["duck","🦆"],["cat","🐈"]],
    meaning:"To waste effort on something that is already finished or hopeless.",
    origin:"Recorded from the mid-1800s, when beating a flagging horse to keep it working was an everyday sight. Beating one that was already dead became the picture of pointless effort. The Victorian MP John Bright is often credited with making it popular in Commons debates.",
    date:"Mid-19th century", year:1850, status:"attested", rebus:"✋🐴💀",
    world:[["American English","beat a dead horse",""]] },
  { id:"cat-bag", pre:"Let the", word:"cat", emo:"🐈", post:"out of the bag", decoys:[["rabbit","🐇"],["pig","🐖"]],
    meaning:"To reveal a secret, usually by accident.",
    origin:"First recorded in the 1760s. Nobody is sure where it comes from, but it sits neatly beside the older warning not to buy a 'pig in a poke' (a pig in a sack) without looking.",
    date:"1760s", year:1760, status:"unknown", rebus:"🐈👜",
    story:"Market swindlers sold cats in sacks, pretending they were piglets, and opening the bag exposed the trick.", storyTrue:false,
    world:[["French","vendre la mèche","to sell the fuse"]] },
  { id:"rain", pre:"It's raining", word:"cats", emo:"🐈", post:"and dogs", decoys:[["frogs","🐸"],["mice","🐁"]],
    meaning:"It is raining very heavily.",
    origin:"Jonathan Swift used 'rain cats and dogs' in 1738, and a play from the 1650s has 'rain dogs and polecats'. Why animals, nobody knows.",
    date:"17th–18th century", year:1650, status:"unknown", rebus:"🌧️🐈🐕",
    story:"Cats and dogs sleeping in thatched roofs slid off when heavy rain made the thatch slippery.", storyTrue:false,
    world:[["French","il pleut des cordes","it's raining ropes"],["Welsh","mae hi'n bwrw hen wragedd a ffyn","it's raining old women and sticks"],["Dutch","het regent pijpenstelen","it's raining pipe stems"]] },
  { id:"birds", pre:"Kill two", word:"birds", emo:"🐦", post:"with one stone", decoys:[["flies","🪰"],["fish","🐟"]],
    meaning:"To achieve two things with a single action.",
    origin:"In English since at least the 17th century; Thomas Hobbes used it in 1656.",
    date:"17th century", year:1656, status:"attested", rebus:"🪨🐦🐦",
    world:[["German","zwei Fliegen mit einer Klappe schlagen","to swat two flies with one swatter"],["Italian","prendere due piccioni con una fava","to catch two pigeons with one bean"]] },
  { id:"donkey", pre:"For", word:"donkey's", emo:"🫏", post:"years", decoys:[["horse's","🐴"],["sheep's","🐑"]],
    meaning:"For a very long time.",
    origin:"Early 20th-century British slang. Probably a pun on 'donkey's ears', which are long, helped along by the belief that donkeys live for ages.",
    date:"Early 20th century", year:1910, status:"likely", rebus:"🫏📅📅📅" },
  { id:"leg", pre:"Pull someone's", word:"leg", emo:"🦵", post:"", decoys:[["arm","💪"],["ear","👂"]],
    meaning:"To tease someone by telling them something untrue.",
    origin:"In print from the late 1800s. Where it comes from is unknown.",
    date:"Late 19th century", year:1880, status:"unknown", rebus:"🤏🦵",
    story:"Relatives pulled on the legs of people being hanged to shorten their suffering.", storyTrue:false,
    world:[["French","mener quelqu'un en bateau","to take someone for a boat ride"]] },
  { id:"herring", pre:"A red", word:"herring", emo:"🐟", post:"", decoys:[["squirrel","🐿️"],["robin","🐦"]],
    meaning:"Something that distracts from the real issue.",
    origin:"A red herring is a kipper: smoked, salted and very smelly. In 1807 the journalist William Cobbett told a story, probably invented, of using one to draw hounds off a hare's scent, as a jibe at a press distracted from real news.",
    date:"1807", year:1807, status:"attested", rebus:"🔴🐟" },
  { id:"trees", pre:"Can't see the wood for the", word:"trees", emo:"🌳", post:"", decoys:[["flowers","🌷"],["mushrooms","🍄"]],
    meaning:"To be so caught up in detail that you miss the bigger picture.",
    origin:"Found in John Heywood's collection of English proverbs from 1546.",
    date:"1546", year:1546, status:"attested", rebus:"🙈🌳🌳🌳",
    world:[["American English","can't see the forest for the trees",""],["German","den Wald vor lauter Bäumen nicht sehen","not to see the forest for all the trees"]] },
  { id:"hatter", pre:"As mad as a", word:"hatter", emo:"🎩", post:"", decoys:[["baker","🥖"],["vicar","⛪"]],
    meaning:"Completely mad.",
    origin:"Felt hat-makers used mercury compounds, and many developed tremors and confusion. The phrase was already in use before Lewis Carroll's Hatter appeared in 1865.",
    date:"1830s", year:1835, status:"likely", rebus:"🤪🎩" },
  { id:"teacup", pre:"A storm in a", word:"teacup", emo:"☕", post:"", decoys:[["bathtub","🛁"],["bucket","🪣"]],
    meaning:"A lot of fuss about something trivial.",
    origin:"The British form dates from the 19th century. The idea is ancient: Cicero wrote of stirring up waves in a ladle.",
    date:"19th century", year:1850, status:"attested", rebus:"⛈️☕",
    world:[["American English","a tempest in a teapot",""],["French","une tempête dans un verre d'eau","a storm in a glass of water"]] },
  { id:"pigs", pre:"", word:"Pigs", emo:"🐖", post:"might fly", decoys:[["Cows","🐄"],["Sheep","🐑"]],
    meaning:"Said of something that will never happen.",
    origin:"The flying pig has stood for impossibility since at least the early 1600s. Lewis Carroll used it in Alice's Adventures in Wonderland.",
    date:"17th century", year:1616, status:"attested", rebus:"🐖🪽",
    world:[["French","quand les poules auront des dents","when hens have teeth"]] },
  { id:"biscuit", pre:"That takes the", word:"biscuit", emo:"🍪", post:"", decoys:[["sandwich","🥪"],["crumpet","🥞"]],
    meaning:"That is the most outrageous or annoying thing yet.",
    origin:"A British take on the American 'takes the cake', from the early 1900s. The cake version is linked to cakes given as prizes in contests.",
    date:"Early 20th century", year:1905, status:"attested", rebus:"🤲🍪",
    world:[["American English","that takes the cake",""]] },
  { id:"dogs", pre:"Let sleeping", word:"dogs", emo:"🐕", post:"lie", decoys:[["cats","🐈"],["bears","🐻"]],
    meaning:"Leave a situation alone rather than stir up trouble.",
    origin:"Chaucer has a version in Troilus and Criseyde in the 1380s: it is no good to wake a sleeping hound.",
    date:"14th century", year:1385, status:"attested", rebus:"😴🐕🐕" },
  { id:"uncle", pre:"…and Bob's your", word:"uncle", emo:"🧔", post:"", decoys:[["aunt","👵"],["dog","🐶"]],
    meaning:"And there you have it; job done.",
    origin:"British, appearing in print from the 1920s–30s. Its origin is unknown.",
    date:"1920s–30s", year:1925, status:"unknown",
    story:"Prime Minister Lord Salisbury (Robert Cecil) gave his nephew Arthur Balfour a top job in 1887, so everyone said 'Bob's your uncle'.", storyTrue:false },
  { id:"tongue", pre:"Has the cat got your", word:"tongue", emo:"👅", post:"", decoys:[["nose","👃"],["teeth","🦷"]],
    meaning:"Why aren't you saying anything?",
    origin:"Recorded from the 19th century. Its origin is unknown.",
    date:"19th century", year:1850, status:"unknown", rebus:"🐈👅",
    story:"It refers to the cat-o'-nine-tails whip, which left sailors too hurt to speak.", storyTrue:false },
  { id:"moon", pre:"Over the", word:"moon", emo:"🌙", post:"", decoys:[["rainbow","🌈"],["hills","⛰️"]],
    meaning:"Extremely happy.",
    origin:"In use from the 18th century. People often connect it to the nursery rhyme where the cow jumps over the moon, but nobody has shown the rhyme came first. Footballers made it a post-match cliché in the 1970s.",
    date:"18th century", year:1750, status:"likely", rebus:"🐄⤴️🌙",
    world:[["French","être aux anges","to be with the angels"]] },
  { id:"parrot", pre:"Sick as a", word:"parrot", emo:"🦜", post:"", decoys:[["pigeon","🕊️"],["budgie","🐤"]],
    meaning:"Bitterly disappointed.",
    origin:"The partner of 'over the moon' in British football interviews from the 1970s. Why a parrot is a mystery; there are theories about parrot fever, but none is proven.",
    date:"1970s", year:1978, status:"unknown", rebus:"🤢🦜" },
  { id:"baby", pre:"Don't throw the", word:"baby", emo:"👶", post:"out with the bathwater", decoys:[["duck","🦆"],["soap","🧼"]],
    meaning:"Don't get rid of something valuable while getting rid of something unwanted.",
    origin:"A German saying from the early 1500s, used by the satirist Thomas Murner. Thomas Carlyle brought it into English in the 1840s.",
    date:"1500s (German); 1840s (English)", year:1849, status:"attested", rebus:"🛁👶🚫",
    story:"Whole medieval families shared one tub of bathwater, and the baby went last when the water was so murky you could lose it.", storyTrue:false,
    world:[["German","das Kind mit dem Bade ausschütten","to pour out the child with the bath"]] },
  { id:"bullet", pre:"Bite the", word:"bullet", emo:"🔫", post:"", decoys:[["biscuit","🍪"],["pillow","🛏️"]],
    meaning:"To face something unpleasant and get on with it.",
    origin:"In print from Rudyard Kipling's 1891 novel The Light that Failed. It is usually linked to patients biting on something hard during surgery without anaesthetic, which is plausible but not proven.",
    date:"1891", year:1891, status:"likely", rebus:"😬🔫" },
  { id:"cold-feet", pre:"Get cold", word:"feet", emo:"🦶", post:"", decoys:[["hands","🤲"],["ears","👂"]],
    meaning:"To lose your nerve just before doing something.",
    origin:"American slang recorded from the 1890s. Where it came from is not known.",
    date:"1890s", year:1893, status:"unknown", rebus:"🥶🦶" },
  { id:"break-leg", pre:"Break a", word:"leg", emo:"🦵", post:"", decoys:[["plate","🍽️"],["nail","💅"]],
    meaning:"Good luck! (said to performers, since wishing them luck directly is thought unlucky).",
    origin:"Theatre slang from the 20th century. Its origin is genuinely unknown, and it has attracted plenty of made-up explanations.",
    date:"20th century", year:1921, status:"unknown", rebus:"💥🦵🎭",
    story:"It refers to John Wilkes Booth breaking his leg after leaping onto the stage when he assassinated Lincoln.", storyTrue:false },
  { id:"cake", pre:"A piece of", word:"cake", emo:"🍰", post:"", decoys:[["toast","🍞"],["pie","🥧"]],
    meaning:"Something very easy.",
    origin:"Recorded from the 1930s and much used by RAF pilots in the Second World War for an easy mission.",
    date:"1930s", year:1936, status:"attested", rebus:"🧩🍰",
    world:[["French","c'est du gâteau","it's cake"]] },
  { id:"blue-moon", pre:"Once in a blue", word:"moon", emo:"🌙", post:"", decoys:[["sky","🌌"],["sun","☀️"]],
    meaning:"Very rarely.",
    origin:"In the 1500s, saying the moon was blue meant saying something absurd. The 'once in a blue moon' form appears in the early 1800s. The calendar sense of a 'blue moon' as a second full moon in a month is much more recent.",
    date:"Early 1800s", year:1830, status:"likely", rebus:"1️⃣🔵🌙",
    world:[["French","tous les trente-six du mois","every 36th of the month"]] },
  { id:"nine-yards", pre:"The whole nine", word:"yards", emo:"📏", post:"", decoys:[["miles","🛣️"],["metres","📐"]],
    meaning:"Everything; the full amount.",
    origin:"American, first found in early-1900s newspapers. It is one of the most argued-over phrases in English, and nobody knows what the nine yards were.",
    date:"Early 1900s", year:1907, status:"unknown", rebus:"💯9️⃣📏",
    story:"Second World War fighter pilots' machine-gun belts were nine yards long, so firing the whole belt meant going all out.", storyTrue:false },
  { id:"ps-qs", pre:"Mind your Ps and", word:"Qs", emo:"🔤", post:"", decoys:[["Xs","❌"],["Zs","💤"]],
    meaning:"Be polite and careful how you behave.",
    origin:"Recorded from the 18th century. Its origin is unknown; the most common guess is children learning letters that look alike.",
    date:"18th century", year:1779, status:"unknown",
    story:"Landlords kept track of the pints and quarts customers drank.", storyTrue:false },
  { id:"hair-dog", pre:"The hair of the", word:"dog", emo:"🐕", post:"", decoys:[["cat","🐈"],["horse","🐴"]],
    meaning:"An alcoholic drink taken to cure a hangover.",
    origin:"Short for 'the hair of the dog that bit you', from an old belief that a dog bite could be treated with a hair from the same dog. It is in John Heywood's proverb collection of 1546.",
    date:"1546", year:1546, status:"attested", rebus:"💇🐕🍺" },
  { id:"arm-leg", pre:"Cost an arm and a", word:"leg", emo:"🦵", post:"", decoys:[["foot","🦶"],["tooth","🦷"]],
    meaning:"Be very expensive.",
    origin:"Mid-20th-century, probably American. Its origin is not known.",
    date:"1940s–50s", year:1949, status:"unknown", rebus:"💰💪🦵",
    story:"Portrait painters charged more for pictures that showed the sitter's arms and legs.", storyTrue:false,
    world:[["French","coûter les yeux de la tête","to cost the eyes of the head"]] },
  { id:"pigeons", pre:"Put the cat among the", word:"pigeons", emo:"🕊️", post:"", decoys:[["mice","🐁"],["goldfish","🐠"]],
    meaning:"To say or do something that causes a stir.",
    origin:"British, from the 20th century. Its early history is hazy, but the picture explains itself.",
    date:"20th century", year:1920, status:"unknown", rebus:"🐈➡️🕊️🕊️" },
  { id:"milk", pre:"No use crying over spilt", word:"milk", emo:"🥛", post:"", decoys:[["tea","🍵"],["milkshake","🥤"]],
    meaning:"There is no point being upset about something that can't be undone.",
    origin:"The Welsh writer James Howell recorded 'no weeping for shed milk' in a proverb collection of 1659.",
    date:"1659", year:1659, status:"attested", rebus:"😭🥛" },
  { id:"cloud", pre:"Every", word:"cloud", emo:"☁️", post:"has a silver lining", decoys:[["storm","⛈️"],["puddle","💧"]],
    meaning:"Every bad situation has something good in it.",
    origin:"The image comes from John Milton's masque Comus (1634), which mentions a dark cloud turning out its silver lining. The proverb form settled in the 19th century.",
    date:"17th century", year:1634, status:"attested", rebus:"☁️🥈" },
  { id:"humble-pie", pre:"Eat humble", word:"pie", emo:"🥧", post:"", decoys:[["cake","🍰"],["crumble","🥣"]],
    meaning:"To admit you were wrong and apologise.",
    origin:"'Umbles' were the offal of a deer, and umble pie was cheaper fare than the venison. The phrase, from the 19th century, is a pun on 'humble'.",
    date:"19th century", year:1830, status:"likely", rebus:"🙇🥧" },
  { id:"penny", pre:"A", word:"penny", emo:"🪙", post:"for your thoughts", decoys:[["pound","💷"],["button","🔘"]],
    meaning:"What are you thinking about?",
    origin:"Recorded in the 16th century, when a penny was worth a good deal more than it is now.",
    date:"16th century", year:1547, status:"attested", rebus:"🪙💭" },
  { id:"sock", pre:"Put a", word:"sock", emo:"🧦", post:"in it", decoys:[["shoe","👞"],["scarf","🧣"]],
    meaning:"Be quiet!",
    origin:"British, from the early 20th century. A popular idea is that people muffled loud gramophone horns with a sock, but that has never been proven.",
    date:"Early 20th century", year:1919, status:"unknown", rebus:"🧦🤐" },
  { id:"full-beans", pre:"Full of", word:"beans", emo:"🫘", post:"", decoys:[["peas","🫛"],["sprouts","🥬"]],
    meaning:"Lively and full of energy.",
    origin:"From the 19th century, probably from horses: a horse fed on beans was said to be frisky.",
    date:"19th century", year:1843, status:"likely", rebus:"⚡🫘" },
  { id:"chew-fat", pre:"Chew the", word:"fat", emo:"🥓", post:"", decoys:[["cud","🐄"],["gum","🍬"]],
    meaning:"To chat idly at length.",
    origin:"Recorded from the late 1800s. There are several theories, including sailors chewing salted fat, but none is confirmed.",
    date:"Late 19th century", year:1885, status:"unknown", rebus:"🗣️🥓" },
  { id:"pear", pre:"It's all gone", word:"pear", emo:"🍐", post:"-shaped", decoys:[["apple","🍎"],["banana","🍌"]],
    meaning:"It has all gone wrong.",
    origin:"British slang recorded from the 1980s, often said to come from the RAF. Why a pear is anyone's guess.",
    date:"1980s", year:1983, status:"unknown", rebus:"📉🍐" },
  { id:"wet-blanket", pre:"A wet", word:"blanket", emo:"🛏️", post:"", decoys:[["sock","🧦"],["towel","🧻"]],
    meaning:"Someone who spoils other people's fun.",
    origin:"From the early 1800s. A wet blanket was used to smother a fire, just as a gloomy person smothers a party.",
    date:"Early 19th century", year:1830, status:"likely", rebus:"💧🛏️" },
  { id:"mickey", pre:"Take the", word:"mickey", emo:"🐭", post:"", decoys:[["biscuit","🍪"],["cake","🍰"]],
    meaning:"To make fun of someone.",
    origin:"British, from the 1950s. It is widely thought to be a polite version of ruder rhyming slang, 'Mickey Bliss'.",
    date:"1950s", year:1950, status:"likely", region:"London (Cockney)" },
  { id:"butter", pre:"Butter wouldn't", word:"melt", emo:"🫠", post:"in her mouth", decoys:[["stick","🥢"],["spread","🧈"]],
    meaning:"She looks innocent, but don't be fooled.",
    origin:"An old one: it is in a French–English phrasebook from 1530.",
    date:"1530", year:1530, status:"attested", rebus:"🧈🚫🫠👄" },
  { id:"bull", pre:"Like a", word:"bull", emo:"🐂", post:"in a china shop", decoys:[["goat","🐐"],["toddler","🧒"]],
    meaning:"Clumsy and careless where care is needed.",
    origin:"Recorded from the 1830s.",
    date:"1830s", year:1834, status:"attested", rebus:"🐂🫖",
    world:[["German","wie ein Elefant im Porzellanladen","like an elephant in a porcelain shop"]] },
  { id:"curiosity", pre:"Curiosity killed the", word:"cat", emo:"🐈", post:"", decoys:[["mouse","🐁"],["parrot","🦜"]],
    meaning:"Being nosy can get you into trouble.",
    origin:"The older form was 'care killed the cat', meaning worry, which Ben Jonson used in 1598. 'Curiosity' replaced 'care' around the turn of the 20th century.",
    date:"1598 (as 'care')", year:1598, status:"attested", rebus:"🧐☠️🐈" },
  { id:"steam", pre:"Let off", word:"steam", emo:"💨", post:"", decoys:[["smoke","🚬"],["fireworks","🎆"]],
    meaning:"To release pent-up energy or anger.",
    origin:"From the 19th century, when steam engines released excess pressure through a valve to avoid bursting.",
    date:"19th century", year:1830, status:"attested", rebus:"🚂💨" },
  { id:"creek", pre:"Up the", word:"creek", emo:"🏞️", post:"without a paddle", decoys:[["river","🌊"],["canal","🚣"]],
    meaning:"In serious trouble with no way out.",
    origin:"American, from the 19th century. It also exists in ruder versions.",
    date:"19th century", year:1848, status:"unknown", rebus:"🛶🚫🏓" },
  { id:"peas", pre:"Like two", word:"peas", emo:"🫛", post:"in a pod", decoys:[["beans","🫘"],["nuts","🥜"]],
    meaning:"Very alike.",
    origin:"The comparison is in John Lyly's Euphues of 1580, as 'like one pea to another'.",
    date:"1580", year:1580, status:"attested", rebus:"2️⃣🫛" },
  { id:"early-bird", pre:"The early", word:"bird", emo:"🐦", post:"catches the worm", decoys:[["hen","🐔"],["owl","🦉"]],
    meaning:"People who act promptly get the advantage.",
    origin:"In John Ray's 1670 collection of English proverbs.",
    date:"1670", year:1670, status:"attested", rebus:"⏰🐦🪱",
    world:[["Spanish","a quien madruga, Dios le ayuda","God helps whoever gets up early"]] },
  { id:"chickens", pre:"Don't count your", word:"chickens", emo:"🐣", post:"before they hatch", decoys:[["sheep","🐑"],["ducks","🦆"]],
    meaning:"Don't rely on something good before it has actually happened.",
    origin:"The idea goes back to an Aesop fable about a milkmaid daydreaming about what her milk will buy. The English phrase is recorded from 1570.",
    date:"1570", year:1570, status:"attested", rebus:"🔢🥚🐣",
    world:[["French","vendre la peau de l'ours avant de l'avoir tué","to sell the bear's skin before killing it"]] },
  { id:"hatchet", pre:"Bury the", word:"hatchet", emo:"🪓", post:"", decoys:[["bone","🦴"],["treasure","💰"]],
    meaning:"To make peace and end a quarrel.",
    origin:"From colonial accounts of peace ceremonies among Indigenous nations of north-east America, who buried weapons to mark the end of hostilities. English uses date from the late 1600s.",
    date:"Late 17th century", year:1680, status:"likely", rebus:"⛏️🪓" },
  { id:"thunder", pre:"Steal someone's", word:"thunder", emo:"⚡", post:"", decoys:[["lightning","🌩️"],["umbrella","☂️"]],
    meaning:"To take the credit or attention someone else was due.",
    origin:"In 1704 the playwright John Dennis invented a new way of making stage thunder for his flop of a play. When another production used his method, he complained that they had stolen his thunder.",
    date:"1704", year:1704, status:"attested", rebus:"🦹⚡" },
  { id:"heels", pre:"Head over", word:"heels", emo:"👠", post:"", decoys:[["toes","🦶"],["knees","🦵"]],
    meaning:"Completely, especially in love.",
    origin:"It started out as 'heels over head' in the 14th century, which makes more sense for a somersault. The words swapped round in the 18th century.",
    date:"14th century", year:1350, status:"attested", rebus:"🙃👠❤️" },
  { id:"skeleton", pre:"A", word:"skeleton", emo:"💀", post:"in the cupboard", decoys:[["ghost","👻"],["mouse","🐁"]],
    meaning:"A shameful secret.",
    origin:"British, from the mid-19th century; the novelist William Makepeace Thackeray used it.",
    date:"Mid-19th century", year:1845, status:"attested", rebus:"💀🚪",
    world:[["American English","a skeleton in the closet",""]] },
  { id:"bucket", pre:"Kick the", word:"bucket", emo:"🪣", post:"", decoys:[["can","🥫"],["ball","⚽"]],
    meaning:"To die.",
    origin:"In a 1785 dictionary of slang. One theory is that 'bucket' was an old word for a beam that animals were hung from, but no one knows for sure.",
    date:"18th century", year:1785, status:"unknown", rebus:"🦶🪣" },
  { id:"dogs-dinner", pre:"A", word:"dog's", emo:"🐕", post:"dinner", decoys:[["cat's","🐈"],["pig's","🐖"]],
    meaning:"A mess.",
    origin:"British, from the 1930s. It is also known as a dog's breakfast.",
    date:"1930s", year:1934, status:"unknown", rebus:"🐕🍽️🤢" },
  { id:"thumb", pre:"A rule of", word:"thumb", emo:"👍", post:"", decoys:[["finger","☝️"],["elbow","💪"]],
    meaning:"A rough practical guide rather than an exact rule.",
    origin:"Recorded from the late 17th century. It probably refers to using a thumb as a rough measuring tool.",
    date:"Late 17th century", year:1692, status:"likely", rebus:"📏👍",
    story:"An old law let husbands beat their wives with a stick no thicker than their thumb.", storyTrue:false },
  { id:"spend-penny", pre:"Spend a", word:"penny", emo:"🪙", post:"", decoys:[["pound","💷"],["fiver","💵"]],
    meaning:"To go to the toilet.",
    origin:"British. Public toilets once had coin-operated locks that took a penny; the euphemism is recorded from the 1940s.",
    date:"1940s", year:1945, status:"likely", rebus:"🪙🚽" },
  { id:"robbery", pre:"It's", word:"daylight", emo:"☀️", post:"robbery", decoys:[["midnight","🌃"],["bank","🏦"]],
    meaning:"A blatant rip-off.",
    origin:"British, from the mid-20th century.",
    date:"Mid-20th century", year:1949, status:"unknown", rebus:"☀️🦹💷",
    story:"It comes from the 1696 window tax, which made people brick up windows and so 'robbed' them of daylight.", storyTrue:false },
  { id:"pink", pre:"Tickled", word:"pink", emo:"🩷", post:"", decoys:[["blue","💙"],["green","💚"]],
    meaning:"Very pleased.",
    origin:"From the early 20th century, from the idea of being tickled until your face goes pink with laughing.",
    date:"Early 20th century", year:1910, status:"likely", rebus:"🪶🩷" },
  { id:"handle", pre:"Fly off the", word:"handle", emo:"🪓", post:"", decoys:[["rails","🛤️"],["shelf","🗄️"]],
    meaning:"To lose your temper suddenly.",
    origin:"American, from the 1820s. It pictures an axe head flying off its handle mid-swing.",
    date:"1820s", year:1825, status:"attested", rebus:"🪓💥" },
  { id:"doghouse", pre:"In the", word:"doghouse", emo:"🐕", post:"", decoys:[["garden","🌷"],["shed","🛖"]],
    meaning:"In disgrace, usually with a partner.",
    origin:"From the early 20th century. In Peter Pan (1904), Mr Darling moves into the dog's kennel as a penance, which may have helped it along.",
    date:"Early 20th century", year:1926, status:"likely", rebus:"😬🐕🏠" },
  { id:"nail", pre:"Hit the", word:"nail", emo:"🔨", post:"on the head", decoys:[["screw","🔩"],["peg","📌"]],
    meaning:"To describe something exactly right.",
    origin:"In English since the 16th century, from carpentry.",
    date:"16th century", year:1550, status:"attested", rebus:"🔨📍🎯" },
  { id:"chips", pre:"Cheap as", word:"chips", emo:"🍟", post:"", decoys:[["crisps","🥔"],["peas","🫛"]],
    meaning:"Very cheap.",
    origin:"British, popular from the 1980s.",
    date:"1980s", year:1983, status:"unknown", rebus:"💷👇🍟" },
  { id:"hair-on", pre:"Keep your", word:"hair", emo:"💇", post:"on", decoys:[["hat","🎩"],["shirt","👕"]],
    meaning:"Calm down!",
    origin:"British, from the late 19th century. The joke is presumably that people tear their hair out when angry.",
    date:"Late 19th century", year:1880, status:"unknown", rebus:"😤💇" },
  { id:"chin", pre:"Keep your", word:"chin", emo:"🙂", post:"up", decoys:[["nose","👃"],["elbows","💪"]],
    meaning:"Stay cheerful in a difficult situation.",
    origin:"From the early 20th century, from holding your head up rather than hanging it.",
    date:"Early 20th century", year:1910, status:"likely", rebus:"⬆️🙂" },
  { id:"bonnet", pre:"Have a", word:"bee", emo:"🐝", post:"in your bonnet", decoys:[["ladybird","🐞"],["moth","🦋"]],
    meaning:"To be obsessed with an idea.",
    origin:"Having 'bees in the head' meant being a bit mad as far back as the 1500s. The bonnet arrived later, in the 18th century.",
    date:"18th century", year:1790, status:"likely", rebus:"🐝👒" },
  { id:"cream", pre:"Like the cat that got the", word:"cream", emo:"🥛", post:"", decoys:[["fish","🐟"],["mouse","🐁"]],
    meaning:"Looking very smug.",
    origin:"From the early 20th century. Cats really do like cream, even if it is bad for them.",
    date:"Early 20th century", year:1920, status:"likely", rebus:"😼🥛" },
  { id:"trousers", pre:"All mouth and no", word:"trousers", emo:"👖", post:"", decoys:[["socks","🧦"],["shoes","👞"]],
    meaning:"All talk and no action.",
    origin:"Northern English, from the 1960s. The older version was 'all mouth and trousers'.",
    date:"1960s", year:1960, status:"unknown", region:"Northern England", rebus:"👄🚫👖" },
  { id:"fish", pre:"Like a", word:"fish", emo:"🐟", post:"out of water", decoys:[["duck","🦆"],["frog","🐸"]],
    meaning:"Uncomfortable in unfamiliar surroundings.",
    origin:"Geoffrey Chaucer used the image in The Canterbury Tales in the 1380s, comparing a monk out of his cloister to a fish out of water.",
    date:"14th century", year:1387, status:"attested", rebus:"🐟🏜️" },
  { id:"elephant", pre:"The", word:"elephant", emo:"🐘", post:"in the room", decoys:[["hippo","🦛"],["giraffe","🦒"]],
    meaning:"An obvious problem that everyone avoids mentioning.",
    origin:"American, from the late 1950s.",
    date:"1950s", year:1959, status:"attested", rebus:"🐘🛋️🤫" },
  { id:"goose", pre:"A wild", word:"goose", emo:"🪿", post:"chase", decoys:[["duck","🦆"],["turkey","🦃"]],
    meaning:"A pointless search for something you won't find.",
    origin:"Shakespeare uses it in Romeo and Juliet (1597), where it is a horse race in which riders follow the leader, like geese flying in formation.",
    date:"1597", year:1597, status:"attested", rebus:"🪿🏃" },
  { id:"sleeve", pre:"Wear your heart on your", word:"sleeve", emo:"👕", post:"", decoys:[["hat","🎩"],["collar","👔"]],
    meaning:"To show your feelings openly.",
    origin:"Shakespeare again: Iago says it in Othello (1604).",
    date:"1604", year:1604, status:"attested", rebus:"❤️👕" },
  { id:"ice", pre:"Break the", word:"ice", emo:"🧊", post:"", decoys:[["glass","🥛"],["bread","🍞"]],
    meaning:"To ease the tension when people first meet.",
    origin:"From the 16th century. It probably comes from ships breaking through ice to open a route.",
    date:"16th century", year:1579, status:"likely", rebus:"🔨🧊" },
  { id:"egg", pre:"Have", word:"egg", emo:"🥚", post:"on your face", decoys:[["jam","🍓"],["custard","🍮"]],
    meaning:"To look foolish after a mistake.",
    origin:"From the mid-20th century. Its origin is unclear.",
    date:"Mid-20th century", year:1950, status:"unknown", rebus:"🥚😳" },
  { id:"pie-sky", pre:"", word:"Pie", emo:"🥧", post:"in the sky", decoys:[["Cake","🍰"],["Scone","🧁"]],
    meaning:"A pleasant idea that is very unlikely to happen.",
    origin:"From 'The Preacher and the Slave', a 1911 protest song by Joe Hill mocking promises of rewards in heaven.",
    date:"1911", year:1911, status:"attested", rebus:"🥧☁️" },
  { id:"bacon", pre:"Bring home the", word:"bacon", emo:"🥓", post:"", decoys:[["sausages","🌭"],["shopping","🛍️"]],
    meaning:"To earn the household's money, or to succeed.",
    origin:"Popular from the early 1900s. It is often linked to a 1906 boxing match, but bacon as a prize is much older.",
    date:"Early 20th century", year:1906, status:"likely", rebus:"🏠🥓" },
  { id:"bush", pre:"Beat about the", word:"bush", emo:"🌳", post:"", decoys:[["hedge","🌿"],["garden","🌷"]],
    meaning:"To avoid getting to the point.",
    origin:"From the 15th century. Hunters paid people to beat bushes to drive out birds; beating about the bush was the preliminary, not the main event.",
    date:"15th century", year:1440, status:"attested", rebus:"🥁🌳",
    world:[["American English","beat around the bush",""]] },
  { id:"lion", pre:"The", word:"lion's", emo:"🦁", post:"share", decoys:[["tiger's","🐯"],["bear's","🐻"]],
    meaning:"The biggest part of something.",
    origin:"From Aesop's fables, where a lion hunts with other animals and then takes everything. In English from the 18th century.",
    date:"18th century", year:1790, status:"attested", rebus:"🦁🍰" },
  { id:"pickle", pre:"In a", word:"pickle", emo:"🥒", post:"", decoys:[["jam","🍓"],["stew","🍲"]],
    meaning:"In a difficult situation.",
    origin:"From the Dutch 'in de pekel zitten', to sit in the pickling brine. Shakespeare uses 'in a pickle' in The Tempest (1611).",
    date:"1611", year:1611, status:"attested", rebus:"😣🥒",
    world:[["Dutch","in de pekel zitten","to sit in the brine"]] },
  { id:"pudding", pre:"Over-egg the", word:"pudding", emo:"🍮", post:"", decoys:[["omelette","🍳"],["toast","🍞"]],
    meaning:"To overdo something, especially by exaggerating.",
    origin:"British. Too many eggs spoil a pudding; the phrase in this sense is mostly 20th century.",
    date:"20th century", year:1950, status:"likely", rebus:"🥚🥚🥚🍮" },
  { id:"kettle", pre:"A different kettle of", word:"fish", emo:"🐟", post:"", decoys:[["tea","🍵"],["soup","🍲"]],
    meaning:"A completely different matter.",
    origin:"'A pretty kettle of fish', meaning a mess, is from the 18th century. The 'different' version came in the early 1900s.",
    date:"18th century", year:1742, status:"likely", rebus:"🫖🐟" },
  { id:"spanner", pre:"Throw a", word:"spanner", emo:"🔧", post:"in the works", decoys:[["teaspoon","🥄"],["sock","🧦"]],
    meaning:"To sabotage a plan or make it go wrong.",
    origin:"British, from the 20th century. The picture is literal: a spanner dropped into machinery wrecks it.",
    date:"20th century", year:1930, status:"attested", rebus:"🔧➡️⚙️",
    world:[["American English","throw a monkey wrench in the works",""]] },
  { id:"coventry", pre:"Send someone to", word:"Coventry", emo:"🏙️", post:"", decoys:[["Swindon","🚉"],["Margate","🏖️"]],
    meaning:"To deliberately ignore someone and refuse to speak to them.",
    origin:"Usually traced to the English Civil War of the 1640s, when captured Royalists were sent to Coventry, a Parliamentarian town where they were given the cold shoulder. The phrase itself turns up in the 18th century, so the link is likely but not certain.",
    date:"18th century", year:1765, status:"likely", rebus:"🤐➡️🏙️" },
  { id:"mutton", pre:"", word:"Mutton", emo:"🐑", post:"dressed as lamb", decoys:[["Beef","🐄"],["Goat","🐐"]],
    meaning:"Someone dressed too young for their age.",
    origin:"Recorded from the early 1800s. Mutton is meat from an older sheep, passed off as the more tender lamb.",
    date:"Early 19th century", year:1811, status:"likely", rebus:"🐑👗" },
  { id:"nosey", pre:"A nosey", word:"parker", emo:"👃", post:"", decoys:[["baker","🥖"],["butler","🤵"]],
    meaning:"A nosy, interfering person.",
    origin:"British, from the early 1900s. Its origin is unknown.",
    date:"Early 20th century", year:1907, status:"unknown", rebus:"👃🔍",
    story:"It is named after Matthew Parker, a meddling Archbishop of Canterbury in the 1500s.", storyTrue:false },
  { id:"burton", pre:"Gone for a", word:"Burton", emo:"🍺", post:"", decoys:[["walk","🚶"],["curry","🍛"]],
    meaning:"Lost, broken, or (originally) killed.",
    origin:"RAF slang from the Second World War, for a pilot who had been killed. Nobody knows who or what Burton was; the favourite guess is a brand of beer.",
    date:"1940s", year:1941, status:"unknown", rebus:"✈️➡️🍺" },
  { id:"clogs", pre:"Pop your", word:"clogs", emo:"🥿", post:"", decoys:[["slippers","🩴"],["wellies","🥾"]],
    meaning:"To die.",
    origin:"British, found in print from the 1970s. 'Pop' can mean to pawn, so one idea is that a dying person no longer needs their clogs, but that is only a guess.",
    date:"1970s", year:1970, status:"unknown", rebus:"💥🥿" },
  { id:"kettle-black", pre:"The pot calling the", word:"kettle", emo:"🫖", post:"black", decoys:[["toaster","🍞"],["teacup","☕"]],
    meaning:"Criticising someone for a fault you have yourself.",
    origin:"The idea is in Thomas Shelton's 1620 English translation of Don Quixote, where a frying pan insults a kettle. Both would have been blackened by the fire.",
    date:"1620", year:1620, status:"attested", rebus:"🍳🗯️🫖⚫",
    world:[["Spanish","dijo la sartén al cazo","the frying pan said to the saucepan"]] },
  { id:"cup-tea", pre:"Not my cup of", word:"tea", emo:"🍵", post:"", decoys:[["coffee","☕"],["soup","🍲"]],
    meaning:"Not something I like.",
    origin:"In the late 1800s a person or thing you liked could be 'my cup of tea'. The negative version took off in the 1920s and 30s.",
    date:"1920s–30s", year:1926, status:"likely", rebus:"🚫☕" },
  { id:"pecker", pre:"Keep your", word:"pecker", emo:"🐦", post:"up", decoys:[["pinky","🤙"],["brolly","☂️"]],
    meaning:"Stay cheerful. (Americans tend to hear something much ruder.)",
    origin:"British, from the 19th century. 'Pecker' meant a bird's beak, and so your nose and chin: keep your head up.",
    date:"19th century", year:1853, status:"attested", rebus:"⬆️🐦" },
  { id:"box-frogs", pre:"As mad as a box of", word:"frogs", emo:"🐸", post:"", decoys:[["kittens","🐈"],["crisps","🥔"]],
    meaning:"Completely bonkers.",
    origin:"British, from the late 20th century. Its origin is unknown, but anyone who has seen a box of frogs understands it.",
    date:"Late 20th century", year:1990, status:"unknown", rebus:"🤪📦🐸" },
  { id:"cobblers", pre:"What a load of", word:"cobblers", emo:"👞", post:"", decoys:[["plumbers","🔧"],["bakers","🥖"]],
    meaning:"Nonsense!",
    origin:"Rhyming slang: 'cobbler's awls' (a shoemaker's tool) stood in for a ruder rhyme. In use from the 20th century.",
    date:"20th century", year:1934, status:"likely", region:"London (Cockney)", rebus:"🗑️👞" },
  { id:"rain-right", pre:"As right as", word:"rain", emo:"🌧️", post:"", decoys:[["sunshine","☀️"],["snow","❄️"]],
    meaning:"Perfectly fine and healthy.",
    origin:"British, from the late 19th century. Why rain counts as right is a mystery, though it probably owes more to the alliteration than the weather.",
    date:"Late 19th century", year:1894, status:"unknown", rebus:"✅🌧️" },
  { id:"lump", pre:"Like it or", word:"lump", emo:"🪨", post:"it", decoys:[["leave","🚪"],["bin","🗑️"]],
    meaning:"Accept it, because you have no choice.",
    origin:"From the 19th century. 'Lump' here is an old dialect word meaning to put up with something unpleasant.",
    date:"19th century", year:1833, status:"likely", rebus:"👍🤷🪨" },
  { id:"sandwiches", pre:"A few", word:"sandwiches", emo:"🥪", post:"short of a picnic", decoys:[["scones","🧁"],["sausages","🌭"]],
    meaning:"Not very bright.",
    origin:"British and Australian slang from the 1980s, one of a family of 'not quite all there' jokes.",
    date:"1980s", year:1987, status:"unknown", rebus:"🧺🥪❓" },
  { id:"old-rope", pre:"Money for old", word:"rope", emo:"🪢", post:"", decoys:[["socks","🧦"],["string","🧵"]],
    meaning:"Very easy money for little effort.",
    origin:"British, from the 20th century. One suggestion is sailors selling off worn-out rope, but nobody knows for sure.",
    date:"20th century", year:1936, status:"unknown", rebus:"💷🪢" },
  { id:"monty", pre:"The full", word:"Monty", emo:"🎩", post:"", decoys:[["Bertie","👔"],["Nigel","🧢"]],
    meaning:"Everything; the whole lot.",
    origin:"British, in print from the 1980s. Its origin is unknown and hotly argued; a 1997 film made it famous around the world.",
    date:"1980s", year:1985, status:"unknown", rebus:"💯🎩",
    story:"It comes from the three-piece suit sold by the tailor Montague Burton.", storyTrue:false },
  { id:"brass-monkey", pre:"It's", word:"brass", emo:"🐒", post:"monkey weather", decoys:[["gold","🥇"],["tin","🥫"]],
    meaning:"It's extremely cold.",
    origin:"From the 19th century, from the ruder saying about the cold freezing parts off a brass monkey. Brass monkeys were cheap ornaments, often the three wise monkeys.",
    date:"19th century", year:1857, status:"unknown", rebus:"🥶🐒",
    story:"It refers to brass racks on warships, called 'monkeys', that shrank in the cold until the cannonballs fell off.", storyTrue:false },
  { id:"french", pre:"Pardon my", word:"French", emo:"🥖", post:"", decoys:[["Latin","🏛️"],["Welsh","🐉"]],
    meaning:"Excuse my swearing.",
    origin:"From the 19th century, when people apologised for dropping French phrases into English conversation. The joke version, for swearing, came later.",
    date:"19th century", year:1830, status:"attested", rebus:"🙏🤬🥖" },
  { id:"mum", pre:"Keep", word:"mum", emo:"🤐", post:"", decoys:[["dad","👨"],["gran","👵"]],
    meaning:"Say nothing; keep quiet.",
    origin:"'Mum' is the sound you make with your lips closed, used for silence since the 1500s. A wartime poster warned 'Keep mum, she's not so dumb'.",
    date:"16th century", year:1540, status:"attested", rebus:"🤐👩" },
  { id:"fiddle", pre:"As fit as a", word:"fiddle", emo:"🎻", post:"", decoys:[["flute","🪈"],["drum","🥁"]],
    meaning:"In very good health.",
    origin:"From the early 1600s, when 'fit' meant suitable or in good order, like a well-tuned instrument.",
    date:"17th century", year:1616, status:"attested", rebus:"💪🎻" },
  { id:"swing-cat", pre:"Not enough room to swing a", word:"cat", emo:"🐈", post:"", decoys:[["handbag","👜"],["hamster","🐹"]],
    meaning:"A very cramped space.",
    origin:"From the 17th century. Whether the cat was the animal or the cat-o'-nine-tails whip, nobody knows.",
    date:"17th century", year:1665, status:"unknown", rebus:"🚫🔄🐈" },
  { id:"wrong-stick", pre:"Get the wrong end of the", word:"stick", emo:"🪵", post:"", decoys:[["spoon","🥄"],["rope","🪢"]],
    meaning:"To misunderstand something completely.",
    origin:"The modern form is from the 19th century. There was a 14th-century version, 'the worse end of the staff', meaning the losing side in a fight.",
    date:"19th century", year:1890, status:"likely", rebus:"❌🔚🪵",
    story:"Romans wiped themselves with a sponge on a stick in shared latrines, and you didn't want the wrong end.", storyTrue:false },
  { id:"butchers", pre:"Have a", word:"butcher's", emo:"🔪", post:"", decoys:[["baker's","🥖"],["barber's","💈"]],
    meaning:"Have a look.",
    origin:"Cockney rhyming slang, from the 1930s: 'butcher's hook' rhymes with 'look'.",
    date:"1930s", year:1936, status:"likely", region:"London (Cockney)", rebus:"👀🔪" },
  { id:"plain-sailing", pre:"It's all", word:"plain", emo:"⛵", post:"sailing", decoys:[["smooth","🧈"],["easy","😌"]],
    meaning:"Easy and free of problems.",
    origin:"From 18th-century navigation. 'Plane sailing' was a simple way of plotting a course that treated the Earth as flat.",
    date:"18th century", year:1750, status:"likely", rebus:"✅⛵" },
  { id:"raspberry", pre:"Blow a", word:"raspberry", emo:"😝", post:"", decoys:[["kiss","💋"],["whistle","📯"]],
    meaning:"To make a rude noise with your tongue and lips.",
    origin:"Rhyming slang, from the late 19th century: 'raspberry tart' rhymes with a much less polite word.",
    date:"Late 19th century", year:1890, status:"likely", region:"London (Cockney)", rebus:"💨🍓" },
  { id:"cream-crackered", pre:"I'm cream", word:"crackered", emo:"🍘", post:"", decoys:[["crumpeted","🥞"],["biscuited","🍪"]],
    meaning:"Exhausted.",
    origin:"Rhyming slang for 'knackered'. Cream crackers are the plain biscuits, so this is a biscuit idiom as well.",
    date:"Late 20th century", year:1980, status:"unknown", region:"London (Cockney)", rebus:"😴🍘" },
  { id:"lum", pre:"Lang may yer lum", word:"reek", emo:"💨", post:"", decoys:[["shine","✨"],["sing","🎶"]],
    meaning:"Long may your chimney smoke: a wish for a long and prosperous life.",
    origin:"A traditional Scots blessing, often heard at New Year. A smoking chimney meant a warm house with fuel to burn.",
    date:"Traditional", year:1800, status:"attested", region:"Scotland", rebus:"🏠💨⏳" },
  { id:"heid", pre:"Keep the", word:"heid", emo:"🧠", post:"", decoys:[["hat","🎩"],["hoose","🏠"]],
    meaning:"Stay calm; don't lose your head.",
    origin:"Scots: 'heid' is head. Its opposite is 'losing the heid'.",
    date:"20th century", year:1900, status:"likely", region:"Scotland", rebus:"😌🧠" },
  { id:"wheesht", pre:"Haud yer", word:"wheesht", emo:"🤫", post:"", decoys:[["whisky","🥃"],["wellies","🥾"]],
    meaning:"Be quiet!",
    origin:"Scots: 'haud' is hold, and 'wheesht' is the sound of shushing someone.",
    date:"Traditional", year:1800, status:"attested", region:"Scotland", rebus:"✋🤫" },
  { id:"muckle", pre:"Many a mickle maks a", word:"muckle", emo:"🪙", post:"", decoys:[["mess","🧹"],["mountain","⛰️"]],
    meaning:"Small amounts add up to a lot.",
    origin:"A garbled Scots proverb. The original was 'many a pickle makes a mickle': a pickle was a tiny amount and a mickle a large one. Since mickle and muckle mean the same thing, the popular version makes no sense at all.",
    date:"18th century", year:1793, status:"attested", region:"Scotland", rebus:"🪙🪙🪙➡️💰" },
  { id:"muck-brass", pre:"Where there's muck there's", word:"brass", emo:"💰", post:"", decoys:[["gold","🥇"],["trouble","⚠️"]],
    meaning:"Dirty or unpleasant work can make good money.",
    origin:"Northern English, especially Yorkshire. 'Brass' is northern slang for money; an older form was 'where there's muck there's money'.",
    date:"19th century", year:1850, status:"likely", region:"Yorkshire", rebus:"💩➡️💰" },
  { id:"say-nowt", pre:"Hear all, see all, say", word:"nowt", emo:"🤐", post:"", decoys:[["summat","💬"],["plenty","📣"]],
    meaning:"Keep your eyes and ears open and your mouth shut.",
    origin:"The traditional Yorkshire motto. It often goes on: 'eat all, sup all, pay nowt', and if you ever do owt for nowt, do it for thysen.",
    date:"Traditional", year:1850, status:"likely", region:"Yorkshire", rebus:"👂👀🤐" },
  { id:"nowt-folk", pre:"There's nowt so queer as", word:"folk", emo:"🧑‍🤝‍🧑", post:"", decoys:[["frogs","🐸"],["fish","🐟"]],
    meaning:"People are very strange.",
    origin:"Northern English. 'Nowt' is nothing, and 'queer' here has its old meaning of odd.",
    date:"Traditional", year:1900, status:"likely", region:"Northern England", rebus:"🤔🧑‍🤝‍🧑" },
  { id:"wood-hole", pre:"Put", word:"wood", emo:"🪵", post:"in th'ole", decoys:[["coal","⚫"],["cake","🍰"]],
    meaning:"Shut the door! (Were you born in a barn?)",
    origin:"Northern English: the wood is the door, and the 'ole is the hole in the wall it should be filling.",
    date:"Traditional", year:1900, status:"likely", region:"Northern England", rebus:"🪵🚪🥶" },
  { id:"apples-pears", pre:"Up the", word:"apples", emo:"🍎", post:"and pears", decoys:[["plums","🫐"],["peaches","🍑"]],
    meaning:"Up the stairs.",
    origin:"Cockney rhyming slang, from the 19th century. It is one of the best known and one of the least actually used.",
    date:"19th century", year:1857, status:"likely", region:"London (Cockney)", rebus:"⬆️🍎🍐" },
  { id:"loaf", pre:"Use your", word:"loaf", emo:"🍞", post:"", decoys:[["bun","🥯"],["crust","🥖"]],
    meaning:"Think about it!",
    origin:"Cockney rhyming slang: 'loaf of bread' rhymes with 'head'. From the early 20th century.",
    date:"Early 20th century", year:1925, status:"likely", region:"London (Cockney)", rebus:"🧠🍞" },
  { id:"porkies", pre:"Telling", word:"porkies", emo:"🥧", post:"", decoys:[["pasties","🥟"],["sausages","🌭"]],
    meaning:"Telling lies.",
    origin:"Rhyming slang: 'pork pies' rhymes with 'lies'. Popular from the 1970s.",
    date:"1970s", year:1975, status:"likely", region:"London (Cockney)", rebus:"🗣️🥧" },
  { id:"rabbiting", pre:"Always", word:"rabbiting", emo:"🐇", post:"on", decoys:[["ferreting","🦦"],["badgering","🦡"]],
    meaning:"Talking on and on about nothing much.",
    origin:"Rhyming slang: 'rabbit and pork' rhymes with 'talk'. From the mid-20th century.",
    date:"Mid-20th century", year:1941, status:"likely", region:"London (Cockney)", rebus:"🐇💬💬💬" },
  { id:"proper-job", pre:"", word:"Proper", emo:"👍", post:"job", decoys:[["Right","✅"],["Grand","🎩"]],
    meaning:"Well done; that's excellent.",
    origin:"West Country, especially Cornwall, where 'proper' is high praise.",
    date:"20th century", year:1950, status:"unknown", region:"West Country", rebus:"👍🔨" },
  { id:"gert-lush", pre:"That's gert", word:"lush", emo:"😍", post:"", decoys:[["posh","🎩"],["damp","💧"]],
    meaning:"That's really lovely.",
    origin:"Bristol slang. 'Gert' means great or very, and 'lush' means lovely.",
    date:"Late 20th century", year:1980, status:"unknown", region:"West Country", rebus:"💯😍" },
  { id:"dreckly", pre:"I'll do it", word:"dreckly", emo:"🐌", post:"", decoys:[["quickly","⚡"],["Tuesday","📅"]],
    meaning:"I'll do it at some point. Possibly.",
    origin:"Cornish and West Country, from 'directly'. It has drifted a long way from meaning immediately; it is often compared to 'mañana', but with less urgency.",
    date:"Traditional", year:1900, status:"likely", region:"West Country", rebus:"🐌⏳" },
  { id:"ay-up-duck", pre:"Ay up me", word:"duck", emo:"🦆", post:"", decoys:[["chicken","🐔"],["goose","🪿"]],
    meaning:"Hello, love.",
    origin:"The East Midlands greeting, also heard around Stoke. Nobody is sure why 'duck' is a term of affection; it may simply be a friendly word like 'chick'. Luciano will be pleased to see another duck.",
    date:"Traditional", year:1900, status:"unknown", region:"East Midlands", rebus:"👋🦆" },
  { id:"now-minute", pre:"I'll do it", word:"now", emo:"⏱️", post:"in a minute", decoys:[["later","🕰️"],["never","🚫"]],
    meaning:"I'll do it soon, but not immediately.",
    origin:"Welsh English. 'Now' means soon-ish, 'now in a minute' means a bit later, and 'now now' means actually now.",
    date:"20th century", year:1950, status:"unknown", region:"Wales", rebus:"⏱️🤷" },
  { id:"tamping", pre:"I'm absolutely", word:"tamping", emo:"😡", post:"", decoys:[["stomping","🦶"],["tapping","👆"]],
    meaning:"Furious.",
    origin:"South Wales. Where the word comes from is unclear.",
    date:"20th century", year:1950, status:"unknown", region:"Wales", rebus:"😡💥" },
  { id:"cwtch", pre:"Come here and give us a", word:"cwtch", emo:"🤗", post:"", decoys:[["kiss","💋"],["coin","🪙"]],
    meaning:"A cuddle (with an extra helping of warmth).",
    origin:"Welsh. A 'cwtch' is a hug, and also a cubbyhole or safe little place. It is said to rhyme with 'butch'.",
    date:"Traditional", year:1900, status:"attested", region:"Wales", rebus:"🤗❤️" },
  { id:"craic", pre:"What's the", word:"craic", emo:"🎉", post:"", decoys:[["news","📰"],["score","🔢"]],
    meaning:"What's going on? Any news or fun?",
    origin:"Ulster and Irish. It started as the English word 'crack', meaning chat, used in Scotland and northern England. The Irish-style spelling 'craic' became popular in the 1970s.",
    date:"20th century", year:1970, status:"attested", region:"Northern Ireland", rebus:"❓🎉" },
  { id:"wee-buns", pre:"Sure that's", word:"wee", emo:"🤏", post:"buns", decoys:[["hot","🔥"],["big","🐘"]],
    meaning:"That's very easy.",
    origin:"Northern Irish slang. Its origin is unknown, but it has the same idea as 'a piece of cake'.",
    date:"Late 20th century", year:1980, status:"unknown", region:"Northern Ireland", rebus:"🤏🧁" },
  { id:"howay", pre:"Howay the", word:"lads", emo:"⚽", post:"", decoys:[["dogs","🐕"],["ducks","🦆"]],
    meaning:"Come on, team!",
    origin:"Geordie, from Newcastle. 'Howay' means come on, and the phrase is the traditional football cheer.",
    date:"20th century", year:1950, status:"likely", region:"North East", rebus:"📣⚽" },
  { id:"coals", pre:"Carrying", word:"coals", emo:"⚫", post:"to Newcastle", decoys:[["sand","🏖️"],["fish","🐟"]],
    meaning:"Doing something pointless, like bringing something to a place that has plenty already.",
    origin:"From the 1600s, when Newcastle was the heart of England's coal trade and shipped it all over the country.",
    date:"17th century", year:1606, status:"attested", region:"North East", rebus:"⚫➡️🏭" },
  { id:"made-up", pre:"I'm made", word:"up", emo:"🥳", post:"", decoys:[["out","🚪"],["over","🔁"]],
    meaning:"I'm delighted.",
    origin:"Scouse, from Liverpool. Its origin is unclear.",
    date:"20th century", year:1960, status:"unknown", region:"Liverpool", rebus:"😁⬆️" }
];
